<a href="https://colab.research.google.com/github/brunobobadilla06/Bruno-CienciaDeDatos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Array en Numpy
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

resultado = array * 2
print(resultado)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
array2 = np.array([10,9,8,7,6,5,4,3,2,1])
resultado = array1 + array2

print(resultado)

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[11 11 11 11 11 11 11 11 11 11]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Array predefinidos
import numpy as np
array = np.zeros((3, 3))
print(array)

array2 = np.ones((3, 3))
print(array2)

array3 = np.eye(3)
print(array3)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
  # Introduccion a Broadcasting
  # Mecanismo que permite a Numpy realizar operaciones aritmeticas en arrays
  # sin crear copias fisicas de los datos
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([1,2,3])
resultado = array1 + array2
print(resultado)
print("-*-*-*-*-*-*-*--*-*-*-***-*-*-*-*-*-*-*-")

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,2,3])
resultado = matriz + vector
print(resultado)
print("-*-*-*-*-*-*-*--*-*-*-***-*-*-*-*-*-*-*-")



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
-*-*-*-*-*-*-*--*-*-*-***-*-*-*-*-*-*-*-
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Funciones estadisticas: Vision general
Herramientas esenciales para analisis descriptivo
1. np.sum()
arr.sum()/np.sum(arr): Calcula la suma de todos los elementos del array(cuando necesitas totales o agregaciones)
2. np.mean()
arr.mean()/np.mean(arr): Calcula el promedio(media aritmetica) de los elementos
3. np.median
np.median(arr): Encuentra el valor central (50% de los datos)
4. np.std()
arr.std()/ np.std(arr): Calcula la desviacion estandar, que mide la dispercion de los datos
5. np.var()
arr.var()/np.var(arr): Calcula la varianza(std al cuadrado)
6. np.min()/max()
arr.min() / arr.max(): Encuentra los valores minimos y maximos en array


In [6]:
# Simulacion de temperaturas diasras (30 dias)
import numpy as np
np.random.seed(42) # Para reproducibilidad

# Generar datos de temperatiras
temperaturas = np.random.normal(22, 5, 30).round(1)

# Estadisticas descriptivas basicas
media = np.mean(temperaturas)
mediana = np.median(temperaturas)
desviacion_estandar = np.std(temperaturas)
minimo = np.min(temperaturas)
maximo = np.max(temperaturas)
rango = maximo - minimo

# Imprimir resultados
print("Temperaturas:")
print(temperaturas)

# Percentiles claves
p25 = np.percentile(temperaturas, 25)
p50 = np.percentile(temperaturas, 50)
p75 = np.percentile(temperaturas, 75)
iqr = p75 - p25

# Imprimir percentiles
print("\nEstadisticas descriptivas:")
print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Desviacion estandar: {desviacion_estandar}")
print(f"Rango: {rango}")

Temperaturas:
[24.5 21.3 25.2 29.6 20.8 20.8 29.9 25.8 19.7 24.7 19.7 19.7 23.2 12.4
 13.4 19.2 16.9 23.6 17.5 14.9 29.3 20.9 22.3 14.9 19.3 22.6 16.2 23.9
 19.  20.5]

Estadisticas descriptivas:
Media: 21.056666666666665
Mediana: 20.8
Desviacion estandar: 4.422343521507823
Rango: 17.5


Estadistica sobre eje y dimensiones
AXIS = Permite aplicar funciones estadisticas a lo largo de diferentes dimensiones de un array, cambiando radicalmente los resultados obtenidos



In [7]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Aplicar funcion estadistica por columnas(axis=0)
col_means = np.mean(array, axis=0)
print("Promedios por columnas:")
print(col_means)

#Aplicar funcion estadistica por filas(axis=1)
row_means = np.mean(array, axis=1)
print("Promedios por filas:")
print(row_means)

# Aplicar sin escificar axis
overall_mean = np.mean(array)
print("Promedio general:")
print(overall_mean)

Promedios por columnas:
[4. 5. 6.]
Promedios por filas:
[2. 5. 8.]
Promedio general:
5.0
